-- Rejected transaction candidates, ported from the C# ExplorerBackend
-- (Database.Main RejectedTransactionCandidate + EP.RejectedTransactions).
--
-- A wallet or user can hold a hash the node still answers on getTransaction while
-- the canonical block's transaction list never included it (mempool-rejected /
-- superseded candidates). The API's /rejected-transactions endpoint captures such
-- diagnostics on demand and serves them from this table, so the explorer can show
-- WHY a hash is not found instead of a bare 404. Additive: no existing table is
-- touched, and nothing in the sync write path writes here.
--
-- Values are stored as the node returned them (text raws, raw response JSON):
-- this is a diagnostic capture, not part of the relational chain model.
CREATE TABLE rejected_transaction_candidates (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash text NOT NULL,
    nexus text NOT NULL,
    chain text NOT NULL,
    block_height bigint,
    block_hash text,
    timestamp_unix_seconds bigint,
    state text,
    result text,
    debug_comment text,
    payload text,
    script_raw text,
    fee_raw text,
    expiration bigint,
    gas_price_raw text,
    gas_limit_raw text,
    sender text,
    gas_payer text,
    gas_target text,
    canonical_status text,
    rpc_response_json text,
    block_response_json text,
    captured_at_unix_seconds bigint NOT NULL,
    updated_at_unix_seconds bigint NOT NULL,
    last_seen_at_unix_seconds bigint NOT NULL
);

-- One candidate per (nexus, chain, hash); re-captures update the row in place.
CREATE UNIQUE INDEX ux_rejected_transaction_candidates_nexus_chain_hash
    ON rejected_transaction_candidates (nexus, chain, hash);
CREATE INDEX ix_rejected_transaction_candidates_hash
    ON rejected_transaction_candidates (hash);
CREATE INDEX ix_rejected_transaction_candidates_captured_at
    ON rejected_transaction_candidates (captured_at_unix_seconds);
