-- Per-chain bookkeeping for the stake-snapshot projector. NOTE: the current forward
-- projector is idempotent and reads/writes nothing here, so this table is presently
-- unused; it is retained (empty, harmless) because the migration is already applied
-- to the baseline database. It can be dropped in a future migration if resumable
-- projector state is never needed.
CREATE TABLE IF NOT EXISTS staking_snapshot_projection_state (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id integer NOT NULL REFERENCES chains(id) ON DELETE CASCADE,
    source text NOT NULL,
    anchor_day_unix_seconds bigint,
    last_projected_day_unix_seconds bigint,
    last_projected_month_unix_seconds bigint,
    updated_at_unix_seconds bigint NOT NULL,
    CONSTRAINT ux_staking_snapshot_projection_state_chain UNIQUE (chain_id)
);

CREATE INDEX IF NOT EXISTS ix_staking_snapshot_projection_state_chain_source
    ON staking_snapshot_projection_state (chain_id, source);
