--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: _sqlx_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public._sqlx_migrations (
    version bigint NOT NULL,
    description text NOT NULL,
    installed_on timestamp with time zone DEFAULT now() NOT NULL,
    success boolean NOT NULL,
    checksum bytea NOT NULL,
    execution_time bigint NOT NULL
);


--
-- Name: address_balances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.address_balances (
    id integer NOT NULL,
    token_id integer NOT NULL,
    address_id integer NOT NULL,
    amount_raw numeric DEFAULT 0.0 NOT NULL
);


--
-- Name: address_balances_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.address_balances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_balances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: address_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.address_transactions (
    address_id integer NOT NULL,
    transaction_id integer NOT NULL,
    timestamp_unix_seconds bigint NOT NULL
);


--
-- Name: address_validator_kinds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.address_validator_kinds (
    id integer NOT NULL,
    name text
);


--
-- Name: address_validator_kinds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.address_validator_kinds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_validator_kinds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: addresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.addresses (
    id integer NOT NULL,
    address text,
    address_name text,
    name_last_updated_unix_seconds bigint NOT NULL,
    unclaimed_amount_raw numeric,
    chain_id integer NOT NULL,
    address_validator_kind_id integer,
    staked_amount_raw numeric,
    stake_timestamp bigint DEFAULT 0 NOT NULL,
    avatar text,
    storage_available bigint DEFAULT 0 NOT NULL,
    storage_used bigint DEFAULT 0 NOT NULL,
    total_soul_amount numeric DEFAULT 0 NOT NULL,
    balance_dirty_block bigint DEFAULT 0 NOT NULL,
    first_tx_unix_seconds bigint
);


--
-- Name: COLUMN addresses.address_validator_kind_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.addresses.address_validator_kind_id IS 'Frozen pre-boundary validator kinds (4 Primary rows = the gen2 validators); no writer since the zero base.';


--
-- Name: COLUMN addresses.avatar; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.addresses.avatar IS 'Frozen pre-boundary account state (2 custom avatars); no writer since the zero base.';


--
-- Name: COLUMN addresses.storage_available; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.addresses.storage_available IS 'Frozen pre-boundary gen1/gen2 account state (8,617 non-zero rows); no writer since the zero base. Preserved deliberately — see the F1 audit finding.';


--
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.blocks (
    id integer NOT NULL,
    height bigint DEFAULT 0 NOT NULL,
    timestamp_unix_seconds bigint NOT NULL,
    chain_id integer NOT NULL,
    hash text,
    protocol integer NOT NULL,
    chain_address_id integer NOT NULL,
    validator_address_id integer NOT NULL,
    reward numeric,
    producer_address_id integer
);


--
-- Name: blocks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.blocks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blocks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chains; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chains (
    id integer NOT NULL,
    name text,
    current_height bigint DEFAULT 0 NOT NULL
);


--
-- Name: COLUMN chains.current_height; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.chains.current_height IS 'Sync cursor, advanced once per committed block; the only mutable column of this dimension.';


--
-- Name: chains_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chains ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chains_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contract_methods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contract_methods (
    id integer NOT NULL,
    contract_id integer NOT NULL,
    methods jsonb NOT NULL,
    timestamp_unix_seconds bigint NOT NULL
);


--
-- Name: contract_methods_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contract_methods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contract_methods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contracts (
    id integer NOT NULL,
    name text,
    hash text,
    symbol text,
    script_raw text,
    chain_id integer NOT NULL,
    address_id integer,
    contract_method_id integer,
    last_updated_unix_seconds bigint NOT NULL,
    create_event_id integer
);


--
-- Name: contracts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contracts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_kinds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_kinds (
    id integer NOT NULL,
    name text
);


--
-- Name: event_kinds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.event_kinds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_kinds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.events (
    id integer NOT NULL,
    timestamp_unix_seconds bigint NOT NULL,
    event_index integer NOT NULL,
    token_id text,
    burned boolean,
    address_id integer NOT NULL,
    chain_id integer NOT NULL,
    contract_id integer NOT NULL,
    transaction_id integer NOT NULL,
    event_kind_id integer NOT NULL,
    nft_id integer,
    target_address_id integer,
    payload_format smallint,
    payload_json jsonb,
    raw_data text,
    event_name text
);


--
-- Name: COLUMN events.token_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.events.token_id IS 'Dual semantics inherited from C#: the NFT instance id for NFT events, the RAW AMOUNT for fungible token events (equals payload token_event.value_raw). Burn accounting depends on it.';


--
-- Name: COLUMN events.burned; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.events.burned IS 'Tri-state in practice: true or NULL, never false. Set retroactively on all of a token''s historical events when it burns; one of only two mutable event columns (the other is nft_id).';


--
-- Name: COLUMN events.payload_format; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.events.payload_format IS '1=legacy.backfill.v1, 2=live.v1, 3=legacy.raw.v1 (undecoded; raw_data holds the bytes), 4=legacy.decoded.v1';


--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: infusions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.infusions (
    id integer NOT NULL,
    key text,
    value text,
    token_id integer,
    nft_id integer NOT NULL
);


--
-- Name: infusions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.infusions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.infusions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nft_ownerships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nft_ownerships (
    id integer NOT NULL,
    last_change_unix_seconds bigint NOT NULL,
    amount integer NOT NULL,
    nft_id integer NOT NULL,
    address_id integer NOT NULL
);


--
-- Name: nft_ownerships_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.nft_ownerships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nft_ownerships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nfts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nfts (
    id integer NOT NULL,
    dm_unix_seconds bigint NOT NULL,
    token_id text,
    token_uri text,
    description text,
    name text,
    rom text,
    ram text,
    image text,
    video text,
    info_url text,
    mint_date_unix_seconds bigint NOT NULL,
    mint_number integer NOT NULL,
    offchain_api_response jsonb,
    chain_api_response jsonb,
    burned boolean,
    nsfw boolean NOT NULL,
    blacklisted boolean NOT NULL,
    metadata_update boolean,
    series_id integer,
    creator_address_id integer,
    chain_id integer NOT NULL,
    contract_id integer NOT NULL,
    infused_into_id integer,
    metadata jsonb
);


--
-- Name: nfts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.nfts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nfts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organization_addresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organization_addresses (
    id integer NOT NULL,
    organization_id integer NOT NULL,
    address_id integer NOT NULL
);


--
-- Name: organization_addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.organization_addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organization_addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organizations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organizations (
    id integer NOT NULL,
    organization_id text,
    name text,
    create_event_id integer,
    address text,
    address_name text
);


--
-- Name: organizations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.organizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organizations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: platforms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.platforms (
    id integer NOT NULL,
    name text,
    chain text,
    fuel text,
    hidden boolean NOT NULL,
    create_event_id integer
);


--
-- Name: platforms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.platforms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.platforms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: series; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.series (
    id integer NOT NULL,
    contract_id integer NOT NULL,
    series_id text,
    current_supply integer NOT NULL,
    max_supply integer NOT NULL,
    series_mode_id integer,
    name text,
    description text,
    image text,
    royalties numeric NOT NULL,
    type integer NOT NULL,
    attr_type_1 text,
    attr_value_1 text,
    attr_type_2 text,
    attr_value_2 text,
    attr_type_3 text,
    attr_value_3 text,
    has_locked boolean NOT NULL,
    nsfw boolean,
    blacklisted boolean,
    dm_unix_seconds bigint NOT NULL,
    creator_address_id integer,
    metadata jsonb,
    series_created_unix_seconds bigint DEFAULT 0 NOT NULL,
    chain_api_response jsonb
);


--
-- Name: series_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.series ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.series_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: series_modes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.series_modes (
    id integer NOT NULL,
    mode_name text
);


--
-- Name: series_modes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.series_modes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.series_modes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: signature_kinds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.signature_kinds (
    id integer NOT NULL,
    name text
);


--
-- Name: signature_kinds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.signature_kinds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.signature_kinds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: signatures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.signatures (
    id integer NOT NULL,
    signature_kind_id integer NOT NULL,
    data bytea,
    transaction_id integer NOT NULL
);


--
-- Name: signatures_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.signatures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.signatures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: soul_masters_monthlies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.soul_masters_monthlies (
    id integer NOT NULL,
    month_unix_seconds bigint NOT NULL,
    masters_count integer NOT NULL,
    captured_at_unix_seconds bigint NOT NULL,
    source text,
    chain_id integer NOT NULL
);


--
-- Name: soul_masters_monthlies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.soul_masters_monthlies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.soul_masters_monthlies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stake_boundary_balances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stake_boundary_balances (
    chain_id integer NOT NULL,
    address text NOT NULL,
    staked_amount_raw text NOT NULL
);


--
-- Name: stake_boundary_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stake_boundary_state (
    chain_id integer NOT NULL,
    boundary_day_unix_seconds bigint NOT NULL,
    soul_supply_raw text NOT NULL,
    masters_count integer NOT NULL,
    stakers_count integer NOT NULL,
    staked_soul_raw text NOT NULL,
    captured_at_unix_seconds bigint NOT NULL,
    source text NOT NULL
);


--
-- Name: stake_snapshot_resume; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stake_snapshot_resume (
    chain_id integer NOT NULL,
    last_projected_day_unix_seconds bigint NOT NULL,
    total_staked_raw numeric NOT NULL,
    soul_supply_raw numeric NOT NULL,
    stakers_count integer NOT NULL,
    masters_count integer NOT NULL
);


--
-- Name: stake_snapshot_resume_stakes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stake_snapshot_resume_stakes (
    chain_id integer NOT NULL,
    address text NOT NULL,
    staked_amount_raw numeric NOT NULL
);


--
-- Name: staking_progress_dailies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.staking_progress_dailies (
    id integer NOT NULL,
    date_unix_seconds bigint NOT NULL,
    staked_soul_raw text,
    soul_supply_raw text,
    stakers_count integer NOT NULL,
    masters_count integer NOT NULL,
    staking_ratio numeric NOT NULL,
    captured_at_unix_seconds bigint NOT NULL,
    source text,
    chain_id integer NOT NULL
);


--
-- Name: staking_progress_dailies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.staking_progress_dailies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.staking_progress_dailies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_daily_prices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_daily_prices (
    id integer NOT NULL,
    date_unix_seconds bigint NOT NULL,
    price_usd numeric NOT NULL,
    token_id integer NOT NULL
);


--
-- Name: token_daily_prices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_daily_prices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_daily_prices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tokens (
    id integer NOT NULL,
    symbol text,
    fungible boolean NOT NULL,
    transferable boolean NOT NULL,
    finite boolean NOT NULL,
    divisible boolean NOT NULL,
    fuel boolean NOT NULL,
    stakable boolean NOT NULL,
    fiat boolean NOT NULL,
    swappable boolean NOT NULL,
    burnable boolean NOT NULL,
    decimals integer NOT NULL,
    script_raw text,
    address_id integer NOT NULL,
    owner_id integer NOT NULL,
    price_usd numeric NOT NULL,
    chain_id integer NOT NULL,
    contract_id integer NOT NULL,
    create_event_id integer,
    burned_supply_raw numeric,
    current_supply_raw numeric,
    max_supply_raw numeric,
    mintable boolean DEFAULT false NOT NULL,
    name text,
    carbon_token_schemas bytea,
    carbon_id bigint,
    metadata jsonb
);


--
-- Name: tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_states; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transaction_states (
    id integer NOT NULL,
    name text
);


--
-- Name: transaction_states_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transaction_states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    id integer NOT NULL,
    hash text,
    tx_index integer NOT NULL,
    block_id integer NOT NULL,
    timestamp_unix_seconds bigint NOT NULL,
    payload text,
    script_raw bytea,
    result text,
    expiration bigint NOT NULL,
    state_id integer NOT NULL,
    sender_id integer NOT NULL,
    gas_payer_id integer NOT NULL,
    gas_target_id integer NOT NULL,
    fee_raw numeric,
    gas_limit_raw numeric,
    gas_price_raw numeric,
    carbon_tx_data bytea,
    carbon_tx_type smallint,
    debug_comment text
);


--
-- Name: COLUMN transactions.hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.transactions.hash IS 'NOT unique by protocol history: 63 pre-boundary hashes appear in more than one block (gen1 double inclusions, Feb-2023 gen2 cluster). Look up via occurrence count + block height/tx index.';


--
-- Name: COLUMN transactions.gas_limit_raw; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.transactions.gas_limit_raw IS 'Raw KCAL atoms; 18446744073709551615 (u64 max) is the legacy unlimited-gas sentinel — the API serves the formatted gas_limit as NULL for it.';


--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: address_balances PK_AddressBalances; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address_balances
    ADD CONSTRAINT "PK_AddressBalances" PRIMARY KEY (id);


--
-- Name: address_transactions PK_AddressTransactions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address_transactions
    ADD CONSTRAINT "PK_AddressTransactions" PRIMARY KEY (address_id, transaction_id);


--
-- Name: address_validator_kinds PK_AddressValidatorKinds; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address_validator_kinds
    ADD CONSTRAINT "PK_AddressValidatorKinds" PRIMARY KEY (id);


--
-- Name: addresses PK_Addresses; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT "PK_Addresses" PRIMARY KEY (id);


--
-- Name: blocks PK_Blocks; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT "PK_Blocks" PRIMARY KEY (id);


--
-- Name: chains PK_Chains; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chains
    ADD CONSTRAINT "PK_Chains" PRIMARY KEY (id);


--
-- Name: contract_methods PK_ContractMethods; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contract_methods
    ADD CONSTRAINT "PK_ContractMethods" PRIMARY KEY (id);


--
-- Name: contracts PK_Contracts; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contracts
    ADD CONSTRAINT "PK_Contracts" PRIMARY KEY (id);


--
-- Name: event_kinds PK_EventKinds; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_kinds
    ADD CONSTRAINT "PK_EventKinds" PRIMARY KEY (id);


--
-- Name: events PK_Events; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT "PK_Events" PRIMARY KEY (id);


--
-- Name: infusions PK_Infusions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.infusions
    ADD CONSTRAINT "PK_Infusions" PRIMARY KEY (id);


--
-- Name: nft_ownerships PK_NftOwnerships; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nft_ownerships
    ADD CONSTRAINT "PK_NftOwnerships" PRIMARY KEY (id);


--
-- Name: nfts PK_Nfts; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nfts
    ADD CONSTRAINT "PK_Nfts" PRIMARY KEY (id);


--
-- Name: organization_addresses PK_OrganizationAddresses; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_addresses
    ADD CONSTRAINT "PK_OrganizationAddresses" PRIMARY KEY (id);


--
-- Name: organizations PK_Organizations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT "PK_Organizations" PRIMARY KEY (id);


--
-- Name: platforms PK_Platforms; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platforms
    ADD CONSTRAINT "PK_Platforms" PRIMARY KEY (id);


--
-- Name: series_modes PK_SeriesModes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.series_modes
    ADD CONSTRAINT "PK_SeriesModes" PRIMARY KEY (id);


--
-- Name: series PK_Serieses; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT "PK_Serieses" PRIMARY KEY (id);


--
-- Name: signature_kinds PK_SignatureKinds; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signature_kinds
    ADD CONSTRAINT "PK_SignatureKinds" PRIMARY KEY (id);


--
-- Name: signatures PK_Signatures; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signatures
    ADD CONSTRAINT "PK_Signatures" PRIMARY KEY (id);


--
-- Name: soul_masters_monthlies PK_SoulMastersMonthlies; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.soul_masters_monthlies
    ADD CONSTRAINT "PK_SoulMastersMonthlies" PRIMARY KEY (id);


--
-- Name: staking_progress_dailies PK_StakingProgressDailies; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staking_progress_dailies
    ADD CONSTRAINT "PK_StakingProgressDailies" PRIMARY KEY (id);


--
-- Name: token_daily_prices PK_TokenDailyPrices; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_daily_prices
    ADD CONSTRAINT "PK_TokenDailyPrices" PRIMARY KEY (id);


--
-- Name: tokens PK_Tokens; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens
    ADD CONSTRAINT "PK_Tokens" PRIMARY KEY (id);


--
-- Name: transaction_states PK_TransactionStates; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_states
    ADD CONSTRAINT "PK_TransactionStates" PRIMARY KEY (id);


--
-- Name: transactions PK_Transactions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT "PK_Transactions" PRIMARY KEY (id);


--
-- Name: _sqlx_migrations _sqlx_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public._sqlx_migrations
    ADD CONSTRAINT _sqlx_migrations_pkey PRIMARY KEY (version);


--
-- Name: stake_snapshot_resume stake_snapshot_resume_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stake_snapshot_resume
    ADD CONSTRAINT stake_snapshot_resume_pkey PRIMARY KEY (chain_id);


--
-- Name: stake_snapshot_resume_stakes stake_snapshot_resume_stakes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stake_snapshot_resume_stakes
    ADD CONSTRAINT stake_snapshot_resume_stakes_pkey PRIMARY KEY (chain_id, address);


--
-- Name: stake_boundary_balances ux_stake_boundary_balances_chain_address; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stake_boundary_balances
    ADD CONSTRAINT ux_stake_boundary_balances_chain_address UNIQUE (chain_id, address);


--
-- Name: stake_boundary_state ux_stake_boundary_state_chain; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stake_boundary_state
    ADD CONSTRAINT ux_stake_boundary_state_chain UNIQUE (chain_id);


--
-- Name: IX_AddressBalances_AddressId_TokenId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_AddressBalances_AddressId_TokenId" ON public.address_balances USING btree (address_id, token_id);


--
-- Name: IX_AddressBalances_TokenId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AddressBalances_TokenId" ON public.address_balances USING btree (token_id);


--
-- Name: IX_AddressTransactions_TransactionId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AddressTransactions_TransactionId" ON public.address_transactions USING btree (transaction_id);


--
-- Name: IX_AddressValidatorKinds_NAME; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AddressValidatorKinds_NAME" ON public.address_validator_kinds USING btree (name);


--
-- Name: IX_Addresses_AddressValidatorKindId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Addresses_AddressValidatorKindId" ON public.addresses USING btree (address_validator_kind_id);


--
-- Name: IX_Addresses_ChainId_ADDRESS; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Addresses_ChainId_ADDRESS" ON public.addresses USING btree (chain_id, address);


--
-- Name: IX_Addresses_ChainId_BALANCE_DIRTY_BLOCK; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Addresses_ChainId_BALANCE_DIRTY_BLOCK" ON public.addresses USING btree (chain_id, balance_dirty_block);


--
-- Name: IX_Addresses_ChainId_FIRST_TX_UNIX_SECONDS; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Addresses_ChainId_FIRST_TX_UNIX_SECONDS" ON public.addresses USING btree (chain_id, first_tx_unix_seconds);


--
-- Name: IX_Addresses_ChainId_NAME_LAST_UPDATED_UNIX_SECONDS; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Addresses_ChainId_NAME_LAST_UPDATED_UNIX_SECONDS" ON public.addresses USING btree (chain_id, name_last_updated_unix_seconds);


--
-- Name: IX_Blocks_HASH; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Blocks_HASH" ON public.blocks USING btree (hash);


--
-- Name: IX_Blocks_ProducerAddressId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Blocks_ProducerAddressId" ON public.blocks USING btree (producer_address_id);


--
-- Name: IX_Blocks_TIMESTAMP_UNIX_SECONDS; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Blocks_TIMESTAMP_UNIX_SECONDS" ON public.blocks USING btree (timestamp_unix_seconds);


--
-- Name: IX_Chains_NAME; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Chains_NAME" ON public.chains USING btree (name);


--
-- Name: IX_ContractMethods_ContractId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ContractMethods_ContractId" ON public.contract_methods USING btree (contract_id);


--
-- Name: IX_Contracts_AddressId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Contracts_AddressId" ON public.contracts USING btree (address_id);


--
-- Name: IX_Contracts_ChainId_HASH; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Contracts_ChainId_HASH" ON public.contracts USING btree (chain_id, hash);


--
-- Name: IX_Contracts_ContractMethodId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Contracts_ContractMethodId" ON public.contracts USING btree (contract_method_id);


--
-- Name: IX_Contracts_CreateEventId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Contracts_CreateEventId" ON public.contracts USING btree (create_event_id);


--
-- Name: IX_EventKinds_NAME; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_EventKinds_NAME" ON public.event_kinds USING btree (name);


--
-- Name: IX_Events_AddressId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Events_AddressId" ON public.events USING btree (address_id);


--
-- Name: IX_Events_ContractId_TOKEN_ID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Events_ContractId_TOKEN_ID" ON public.events USING btree (contract_id, token_id);


--
-- Name: IX_Events_EventKindId_ID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Events_EventKindId_ID" ON public.events USING btree (event_kind_id, id);


--
-- Name: IX_Events_EventKindId_Timestamp_Id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Events_EventKindId_Timestamp_Id" ON public.events USING btree (event_kind_id, timestamp_unix_seconds, id);


--
-- Name: IX_Events_NftId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Events_NftId" ON public.events USING btree (nft_id);


--
-- Name: IX_Events_TargetAddressId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Events_TargetAddressId" ON public.events USING btree (target_address_id);


--
-- Name: IX_Infusions_KEY; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Infusions_KEY" ON public.infusions USING btree (key);


--
-- Name: IX_Infusions_NftId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Infusions_NftId" ON public.infusions USING btree (nft_id);


--
-- Name: IX_Infusions_TokenId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Infusions_TokenId" ON public.infusions USING btree (token_id);


--
-- Name: IX_NftOwnerships_AddressId_NftId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_NftOwnerships_AddressId_NftId" ON public.nft_ownerships USING btree (address_id, nft_id);


--
-- Name: IX_NftOwnerships_LAST_CHANGE_UNIX_SECONDS; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_NftOwnerships_LAST_CHANGE_UNIX_SECONDS" ON public.nft_ownerships USING btree (last_change_unix_seconds);


--
-- Name: IX_NftOwnerships_NftId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_NftOwnerships_NftId" ON public.nft_ownerships USING btree (nft_id);


--
-- Name: IX_Nfts_ContractId_TOKEN_ID; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Nfts_ContractId_TOKEN_ID" ON public.nfts USING btree (contract_id, token_id);


--
-- Name: IX_Nfts_ContractId_TOKEN_URI; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Nfts_ContractId_TOKEN_URI" ON public.nfts USING btree (contract_id, token_uri);


--
-- Name: IX_Nfts_CreatorAddressId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Nfts_CreatorAddressId" ON public.nfts USING btree (creator_address_id);


--
-- Name: IX_Nfts_InfusedIntoId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Nfts_InfusedIntoId" ON public.nfts USING btree (infused_into_id);


--
-- Name: IX_Nfts_SeriesId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Nfts_SeriesId" ON public.nfts USING btree (series_id);


--
-- Name: IX_Nfts_TOKEN_ID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Nfts_TOKEN_ID" ON public.nfts USING btree (token_id);


--
-- Name: IX_OrganizationAddresses_AddressId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_OrganizationAddresses_AddressId" ON public.organization_addresses USING btree (address_id);


--
-- Name: IX_OrganizationAddresses_OrganizationId_AddressId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_OrganizationAddresses_OrganizationId_AddressId" ON public.organization_addresses USING btree (organization_id, address_id);


--
-- Name: IX_Organizations_CreateEventId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Organizations_CreateEventId" ON public.organizations USING btree (create_event_id);


--
-- Name: IX_Organizations_NAME; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Organizations_NAME" ON public.organizations USING btree (name);


--
-- Name: IX_Platforms_CreateEventId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Platforms_CreateEventId" ON public.platforms USING btree (create_event_id);


--
-- Name: IX_Platforms_NAME; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Platforms_NAME" ON public.platforms USING btree (name);


--
-- Name: IX_Search_Blocks_Height; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Search_Blocks_Height" ON public.blocks USING btree (height);


--
-- Name: IX_SeriesModes_MODE_NAME; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_SeriesModes_MODE_NAME" ON public.series_modes USING btree (mode_name);


--
-- Name: IX_Serieses_ContractId_SERIES_ID; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Serieses_ContractId_SERIES_ID" ON public.series USING btree (contract_id, series_id);


--
-- Name: IX_Serieses_CreatorAddressId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Serieses_CreatorAddressId" ON public.series USING btree (creator_address_id);


--
-- Name: IX_Serieses_SERIES_CREATED_UNIX_SECONDS_ID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Serieses_SERIES_CREATED_UNIX_SECONDS_ID" ON public.series USING btree (series_created_unix_seconds, id);


--
-- Name: IX_Serieses_SERIES_ID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Serieses_SERIES_ID" ON public.series USING btree (series_id);


--
-- Name: IX_Serieses_SeriesModeId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Serieses_SeriesModeId" ON public.series USING btree (series_mode_id);


--
-- Name: IX_SignatureKinds_NAME; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_SignatureKinds_NAME" ON public.signature_kinds USING btree (name);


--
-- Name: IX_Signatures_TransactionId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Signatures_TransactionId" ON public.signatures USING btree (transaction_id);


--
-- Name: IX_SoulMastersMonthlies_ChainId_MONTH_UNIX_SECONDS; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_SoulMastersMonthlies_ChainId_MONTH_UNIX_SECONDS" ON public.soul_masters_monthlies USING btree (chain_id, month_unix_seconds);


--
-- Name: IX_StakingProgressDailies_ChainId_DATE_UNIX_SECONDS; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_StakingProgressDailies_ChainId_DATE_UNIX_SECONDS" ON public.staking_progress_dailies USING btree (chain_id, date_unix_seconds);


--
-- Name: IX_TokenDailyPrices_DATE_UNIX_SECONDS; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_TokenDailyPrices_DATE_UNIX_SECONDS" ON public.token_daily_prices USING btree (date_unix_seconds);


--
-- Name: IX_Tokens_AddressId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Tokens_AddressId" ON public.tokens USING btree (address_id);


--
-- Name: IX_Tokens_ChainId_ContractId_SYMBOL; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Tokens_ChainId_ContractId_SYMBOL" ON public.tokens USING btree (chain_id, contract_id, symbol);


--
-- Name: IX_Tokens_CreateEventId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Tokens_CreateEventId" ON public.tokens USING btree (create_event_id);


--
-- Name: IX_Tokens_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Tokens_OwnerId" ON public.tokens USING btree (owner_id);


--
-- Name: IX_Tokens_SYMBOL_ChainId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Tokens_SYMBOL_ChainId" ON public.tokens USING btree (symbol, chain_id);


--
-- Name: IX_TransactionStates_NAME; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_TransactionStates_NAME" ON public.transaction_states USING btree (name);


--
-- Name: IX_Transactions_GasPayerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Transactions_GasPayerId" ON public.transactions USING btree (gas_payer_id);


--
-- Name: IX_Transactions_GasTargetId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Transactions_GasTargetId" ON public.transactions USING btree (gas_target_id);


--
-- Name: IX_Transactions_HASH; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Transactions_HASH" ON public.transactions USING btree (hash);


--
-- Name: IX_Transactions_SenderId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Transactions_SenderId" ON public.transactions USING btree (sender_id);


--
-- Name: IX_Transactions_TIMESTAMP_UNIX_SECONDS_ID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Transactions_TIMESTAMP_UNIX_SECONDS_ID" ON public.transactions USING btree (timestamp_unix_seconds, id);


--
-- Name: ix_address_transactions_address_timestamp_tx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_address_transactions_address_timestamp_tx ON public.address_transactions USING btree (address_id, timestamp_unix_seconds, transaction_id);


--
-- Name: ix_addresses_address; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_addresses_address ON public.addresses USING btree (address);


--
-- Name: ix_addresses_address_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_addresses_address_name ON public.addresses USING btree (address_name) WHERE (address_name IS NOT NULL);


--
-- Name: ix_addresses_chain_soul; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_addresses_chain_soul ON public.addresses USING btree (chain_id, total_soul_amount DESC, id);


--
-- Name: ix_events_burn_lookup_chain_contract_token_kind; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_events_burn_lookup_chain_contract_token_kind ON public.events USING btree (chain_id, contract_id, token_id, event_kind_id) WHERE (token_id IS NOT NULL);


--
-- Name: ix_events_timestamp_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_events_timestamp_id ON public.events USING btree (timestamp_unix_seconds, id);


--
-- Name: ix_stake_boundary_balances_chain; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_stake_boundary_balances_chain ON public.stake_boundary_balances USING btree (chain_id);


--
-- Name: ix_tokens_chain_carbon_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_tokens_chain_carbon_id ON public.tokens USING btree (chain_id, carbon_id) WHERE (carbon_id IS NOT NULL);


--
-- Name: ix_transactions_state_timestamp_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_transactions_state_timestamp_id ON public.transactions USING btree (state_id, timestamp_unix_seconds DESC, id DESC);


--
-- Name: ux_blocks_chain_height; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_blocks_chain_height ON public.blocks USING btree (chain_id, height);


--
-- Name: ux_events_transaction_event_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_events_transaction_event_index ON public.events USING btree (transaction_id, event_index);


--
-- Name: ux_token_daily_prices_token_date; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_token_daily_prices_token_date ON public.token_daily_prices USING btree (token_id, date_unix_seconds);


--
-- Name: ux_transactions_block_tx_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_transactions_block_tx_index ON public.transactions USING btree (block_id, tx_index);


--
-- Name: address_balances FK_AddressBalances_Addresses_AddressId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address_balances
    ADD CONSTRAINT "FK_AddressBalances_Addresses_AddressId" FOREIGN KEY (address_id) REFERENCES public.addresses(id) ON DELETE CASCADE;


--
-- Name: address_balances FK_AddressBalances_Tokens_TokenId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address_balances
    ADD CONSTRAINT "FK_AddressBalances_Tokens_TokenId" FOREIGN KEY (token_id) REFERENCES public.tokens(id) ON DELETE CASCADE;


--
-- Name: address_transactions FK_AddressTransactions_Addresses_AddressId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address_transactions
    ADD CONSTRAINT "FK_AddressTransactions_Addresses_AddressId" FOREIGN KEY (address_id) REFERENCES public.addresses(id) ON DELETE CASCADE;


--
-- Name: address_transactions FK_AddressTransactions_Transactions_TransactionId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address_transactions
    ADD CONSTRAINT "FK_AddressTransactions_Transactions_TransactionId" FOREIGN KEY (transaction_id) REFERENCES public.transactions(id) ON DELETE CASCADE;


--
-- Name: addresses FK_Addresses_AddressValidatorKinds_AddressValidatorKindId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT "FK_Addresses_AddressValidatorKinds_AddressValidatorKindId" FOREIGN KEY (address_validator_kind_id) REFERENCES public.address_validator_kinds(id);


--
-- Name: addresses FK_Addresses_Chains_ChainId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT "FK_Addresses_Chains_ChainId" FOREIGN KEY (chain_id) REFERENCES public.chains(id);


--
-- Name: blocks FK_Blocks_Addresses_ChainAddressId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT "FK_Blocks_Addresses_ChainAddressId" FOREIGN KEY (chain_address_id) REFERENCES public.addresses(id);


--
-- Name: blocks FK_Blocks_Addresses_ValidatorAddressId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT "FK_Blocks_Addresses_ValidatorAddressId" FOREIGN KEY (validator_address_id) REFERENCES public.addresses(id);


--
-- Name: blocks FK_Blocks_Chains_ChainId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT "FK_Blocks_Chains_ChainId" FOREIGN KEY (chain_id) REFERENCES public.chains(id);


--
-- Name: contract_methods FK_ContractMethods_Contracts_ContractId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contract_methods
    ADD CONSTRAINT "FK_ContractMethods_Contracts_ContractId" FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON DELETE CASCADE;


--
-- Name: contracts FK_Contracts_Addresses_AddressId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contracts
    ADD CONSTRAINT "FK_Contracts_Addresses_AddressId" FOREIGN KEY (address_id) REFERENCES public.addresses(id);


--
-- Name: contracts FK_Contracts_Chains_ChainId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contracts
    ADD CONSTRAINT "FK_Contracts_Chains_ChainId" FOREIGN KEY (chain_id) REFERENCES public.chains(id);


--
-- Name: contracts FK_Contracts_ContractMethods_ContractMethodId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contracts
    ADD CONSTRAINT "FK_Contracts_ContractMethods_ContractMethodId" FOREIGN KEY (contract_method_id) REFERENCES public.contract_methods(id);


--
-- Name: contracts FK_Contracts_Events_CreateEventId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contracts
    ADD CONSTRAINT "FK_Contracts_Events_CreateEventId" FOREIGN KEY (create_event_id) REFERENCES public.events(id);


--
-- Name: events FK_Events_Addresses_AddressId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT "FK_Events_Addresses_AddressId" FOREIGN KEY (address_id) REFERENCES public.addresses(id);


--
-- Name: events FK_Events_Addresses_TargetAddressId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT "FK_Events_Addresses_TargetAddressId" FOREIGN KEY (target_address_id) REFERENCES public.addresses(id);


--
-- Name: events FK_Events_Chains_ChainId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT "FK_Events_Chains_ChainId" FOREIGN KEY (chain_id) REFERENCES public.chains(id);


--
-- Name: events FK_Events_Contracts_ContractId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT "FK_Events_Contracts_ContractId" FOREIGN KEY (contract_id) REFERENCES public.contracts(id);


--
-- Name: events FK_Events_EventKinds_EventKindId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT "FK_Events_EventKinds_EventKindId" FOREIGN KEY (event_kind_id) REFERENCES public.event_kinds(id);


--
-- Name: events FK_Events_Nfts_NftId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT "FK_Events_Nfts_NftId" FOREIGN KEY (nft_id) REFERENCES public.nfts(id);


--
-- Name: events FK_Events_Transactions_TransactionId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT "FK_Events_Transactions_TransactionId" FOREIGN KEY (transaction_id) REFERENCES public.transactions(id) ON DELETE CASCADE;


--
-- Name: infusions FK_Infusions_Nfts_NftId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.infusions
    ADD CONSTRAINT "FK_Infusions_Nfts_NftId" FOREIGN KEY (nft_id) REFERENCES public.nfts(id);


--
-- Name: infusions FK_Infusions_Tokens_TokenId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.infusions
    ADD CONSTRAINT "FK_Infusions_Tokens_TokenId" FOREIGN KEY (token_id) REFERENCES public.tokens(id);


--
-- Name: nft_ownerships FK_NftOwnerships_Addresses_AddressId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nft_ownerships
    ADD CONSTRAINT "FK_NftOwnerships_Addresses_AddressId" FOREIGN KEY (address_id) REFERENCES public.addresses(id) ON DELETE CASCADE;


--
-- Name: nft_ownerships FK_NftOwnerships_Nfts_NftId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nft_ownerships
    ADD CONSTRAINT "FK_NftOwnerships_Nfts_NftId" FOREIGN KEY (nft_id) REFERENCES public.nfts(id) ON DELETE CASCADE;


--
-- Name: nfts FK_Nfts_Addresses_CreatorAddressId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nfts
    ADD CONSTRAINT "FK_Nfts_Addresses_CreatorAddressId" FOREIGN KEY (creator_address_id) REFERENCES public.addresses(id);


--
-- Name: nfts FK_Nfts_Chains_ChainId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nfts
    ADD CONSTRAINT "FK_Nfts_Chains_ChainId" FOREIGN KEY (chain_id) REFERENCES public.chains(id);


--
-- Name: nfts FK_Nfts_Contracts_ContractId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nfts
    ADD CONSTRAINT "FK_Nfts_Contracts_ContractId" FOREIGN KEY (contract_id) REFERENCES public.contracts(id);


--
-- Name: nfts FK_Nfts_Nfts_InfusedIntoId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nfts
    ADD CONSTRAINT "FK_Nfts_Nfts_InfusedIntoId" FOREIGN KEY (infused_into_id) REFERENCES public.nfts(id);


--
-- Name: nfts FK_Nfts_Serieses_SeriesId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nfts
    ADD CONSTRAINT "FK_Nfts_Serieses_SeriesId" FOREIGN KEY (series_id) REFERENCES public.series(id);


--
-- Name: organization_addresses FK_OrganizationAddresses_Addresses_AddressId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_addresses
    ADD CONSTRAINT "FK_OrganizationAddresses_Addresses_AddressId" FOREIGN KEY (address_id) REFERENCES public.addresses(id) ON DELETE CASCADE;


--
-- Name: organization_addresses FK_OrganizationAddresses_Organizations_OrganizationId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_addresses
    ADD CONSTRAINT "FK_OrganizationAddresses_Organizations_OrganizationId" FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE;


--
-- Name: organizations FK_Organizations_Events_CreateEventId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT "FK_Organizations_Events_CreateEventId" FOREIGN KEY (create_event_id) REFERENCES public.events(id);


--
-- Name: platforms FK_Platforms_Events_CreateEventId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platforms
    ADD CONSTRAINT "FK_Platforms_Events_CreateEventId" FOREIGN KEY (create_event_id) REFERENCES public.events(id);


--
-- Name: series FK_Serieses_Addresses_CreatorAddressId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT "FK_Serieses_Addresses_CreatorAddressId" FOREIGN KEY (creator_address_id) REFERENCES public.addresses(id);


--
-- Name: series FK_Serieses_Contracts_ContractId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT "FK_Serieses_Contracts_ContractId" FOREIGN KEY (contract_id) REFERENCES public.contracts(id);


--
-- Name: series FK_Serieses_SeriesModes_SeriesModeId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT "FK_Serieses_SeriesModes_SeriesModeId" FOREIGN KEY (series_mode_id) REFERENCES public.series_modes(id);


--
-- Name: signatures FK_Signatures_SignatureKinds_SignatureKindId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signatures
    ADD CONSTRAINT "FK_Signatures_SignatureKinds_SignatureKindId" FOREIGN KEY (signature_kind_id) REFERENCES public.signature_kinds(id);


--
-- Name: signatures FK_Signatures_Transactions_TransactionId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signatures
    ADD CONSTRAINT "FK_Signatures_Transactions_TransactionId" FOREIGN KEY (transaction_id) REFERENCES public.transactions(id) ON DELETE CASCADE;


--
-- Name: soul_masters_monthlies FK_SoulMastersMonthlies_Chains_ChainId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.soul_masters_monthlies
    ADD CONSTRAINT "FK_SoulMastersMonthlies_Chains_ChainId" FOREIGN KEY (chain_id) REFERENCES public.chains(id) ON DELETE CASCADE;


--
-- Name: staking_progress_dailies FK_StakingProgressDailies_Chains_ChainId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staking_progress_dailies
    ADD CONSTRAINT "FK_StakingProgressDailies_Chains_ChainId" FOREIGN KEY (chain_id) REFERENCES public.chains(id) ON DELETE CASCADE;


--
-- Name: token_daily_prices FK_TokenDailyPrices_Tokens_TokenId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_daily_prices
    ADD CONSTRAINT "FK_TokenDailyPrices_Tokens_TokenId" FOREIGN KEY (token_id) REFERENCES public.tokens(id) ON DELETE CASCADE;


--
-- Name: tokens FK_Tokens_Addresses_AddressId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens
    ADD CONSTRAINT "FK_Tokens_Addresses_AddressId" FOREIGN KEY (address_id) REFERENCES public.addresses(id);


--
-- Name: tokens FK_Tokens_Addresses_OwnerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens
    ADD CONSTRAINT "FK_Tokens_Addresses_OwnerId" FOREIGN KEY (owner_id) REFERENCES public.addresses(id);


--
-- Name: tokens FK_Tokens_Chains_ChainId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens
    ADD CONSTRAINT "FK_Tokens_Chains_ChainId" FOREIGN KEY (chain_id) REFERENCES public.chains(id);


--
-- Name: tokens FK_Tokens_Events_CreateEventId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens
    ADD CONSTRAINT "FK_Tokens_Events_CreateEventId" FOREIGN KEY (create_event_id) REFERENCES public.events(id);


--
-- Name: transactions FK_Transactions_Addresses_GasPayerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT "FK_Transactions_Addresses_GasPayerId" FOREIGN KEY (gas_payer_id) REFERENCES public.addresses(id);


--
-- Name: transactions FK_Transactions_Addresses_GasTargetId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT "FK_Transactions_Addresses_GasTargetId" FOREIGN KEY (gas_target_id) REFERENCES public.addresses(id);


--
-- Name: transactions FK_Transactions_Addresses_SenderId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT "FK_Transactions_Addresses_SenderId" FOREIGN KEY (sender_id) REFERENCES public.addresses(id);


--
-- Name: transactions FK_Transactions_Blocks_BlockId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT "FK_Transactions_Blocks_BlockId" FOREIGN KEY (block_id) REFERENCES public.blocks(id) ON DELETE CASCADE;


--
-- Name: transactions FK_Transactions_TransactionStates_StateId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT "FK_Transactions_TransactionStates_StateId" FOREIGN KEY (state_id) REFERENCES public.transaction_states(id);


--
-- Name: blocks blocks_producer_address_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT blocks_producer_address_id_fkey FOREIGN KEY (producer_address_id) REFERENCES public.addresses(id);


--
-- Name: stake_boundary_balances stake_boundary_balances_chain_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stake_boundary_balances
    ADD CONSTRAINT stake_boundary_balances_chain_id_fkey FOREIGN KEY (chain_id) REFERENCES public.chains(id) ON DELETE CASCADE;


--
-- Name: stake_boundary_state stake_boundary_state_chain_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stake_boundary_state
    ADD CONSTRAINT stake_boundary_state_chain_id_fkey FOREIGN KEY (chain_id) REFERENCES public.chains(id) ON DELETE CASCADE;


--
-- Name: stake_snapshot_resume stake_snapshot_resume_chain_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stake_snapshot_resume
    ADD CONSTRAINT stake_snapshot_resume_chain_id_fkey FOREIGN KEY (chain_id) REFERENCES public.chains(id);


--
-- Name: stake_snapshot_resume_stakes stake_snapshot_resume_stakes_chain_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stake_snapshot_resume_stakes
    ADD CONSTRAINT stake_snapshot_resume_stakes_chain_id_fkey FOREIGN KEY (chain_id) REFERENCES public.chains(id);


--
-- PostgreSQL database dump complete
--

